### ISSUE TITLE
iOS Carsh: NSInvalidArgumentException

### ISSUE THREAD

**Issue by fingerart** [adjust/flutter_sdk#104]
![DiixgtvmM6](https://user-images.githubusercontent.com/6304197/217986888-2d5a8a13-5c82-4f5e-b6f0-17fdcfc55ddf.jpg)

**Comment by zhanglexiaoge** [comment]
I have the same problem

**Comment by zhanglexiaoge** [comment]
* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

**Comment by uerceg** [comment]
Hi guys,

Thanks for reporting this. We'll take a look into this and keep you posted. Few questions:

1. Which Adjust Flutter SDK version are you using?
2. Did you start to notice this as soon as your app with that Adjust Flutter SDK version got published to the App Store or is it that you already had the app released and this started all of a sudden (February 7th from the Crashlytics screenshot)?

**Comment by zhanglexiaoge** [comment]
> Hi guys,
> 
> Thanks for reporting this. We'll take a look into this and keep you posted. Few questions:
> 
> 1. Which Adjust Flutter SDK version are you using?
> 2. Did you start to notice this as soon as your app with that Adjust Flutter SDK version got published to the App Store or is it that you already had the app released and this started all of a sudden (February 7th from the Crashlytics screenshot)?

adjust_sdk: ^4.33.0

**Comment by uerceg** [comment]
Thanks for the additional info. We have just shipped Adjust Flutter SDK v4.33.1 which should hopefully address this issue. Feel free to give it a shot and let us know if this version fixes the issue on your end. Looking forward to hearing back from you.

**Comment by zhanglexiaoge** [comment]
> 感谢您提供更多信息。我们刚刚发布了 Adjust Flutter SDK v4.33.1，有望解决这个问题。请随时试一试，如果此版本解决了您的问题，请告诉我们。期待您的回音。

Thanks ,Adjust Flutter SDK v4.33.1  The problem has been solved ，

**Comment by uerceg** [comment]
Great news, thanks for the update @zhanglexiaoge. If I may ask, how were you able to confirm this so quickly? :) Did you manage to have your iOS app released in the App Store from the moment we shipped an SDK update and by the time you wrote this last comment?

**Comment by uerceg** [comment]
Nonetheless, thanks for reporting that the issue has been fixed and in case needed in future, feel free to comment / reopen. Cheers.
