### ISSUE TITLE
Pausing handlers due to SDK being disabled.

### ISSUE THREAD

**Issue by temaand1** [adjust/flutter_sdk#120]
On android, during the session, we saw "Pausing handlers due to SDK being disabled" message in the logs. and Adjust will stop transmitting events to the server. We don't use Adjust.setEnabled(false) in our code, it happens by itself.

**Comment by uerceg** [comment]
Hello there @temaand1,

Could it be that you're trying to run tests with the GDPR forgotten device?

**Comment by temaand1** [comment]
Hey @uerceg, Yes, before the tests, I delete the application from the device and then click Forget device in Test console. 

The problem is solved by the fact that we added a check before each event (`Adjust.IsEnabled()` and if it's return false we call `Adjust.setEnabled(true)`). With these changes, events come as needed, but I wonder why this is happening and whether it will affect anything else.

**Comment by uerceg** [comment]
Can you maybe run the test where you're gonna install and run your app with the Adjust SDK being set in sandbox environment (and log level set to verbose) and then do this test where you're getting this message? Just to see what's actually happening in this case. Also feel free to omit any sensitive data from the logs (app / event token(s), whatever you feel like not sharing).

**Comment by temaand1** [comment]
@uerceg Sure, here it is.
[verbose.txt](https://github.com/adjust/flutter_sdk/files/13439916/verbose.txt)

**Comment by uerceg** [comment]
Thanks for the logs. In theory the line you're seeing is originating from [here](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-core/src/main/java/com/adjust/sdk/ActivityHandler.java#L1793). And that can happen only if one would make `Adjust.setEnabled(false);` method call.

According to what you wrote [here](https://github.com/adjust/flutter_sdk/issues/120#issuecomment-1822734349) it seems like you're gonna engage in re-enabling of the SDK which, yes, it is definitely a prerequisite in order for SDK to be able to track events (if one attempts to track events with SDK being disabled, they are dropped, not even queued).

Not sure how much in depth you wanna go, but I'm curious what's the use case you are trying to solve with having such a usage of calls to `setEnabled` and `isEnabled` methods?

**Comment by temaand1** [comment]
@uerceg Understood. Thank you for response.

If we talking about `isEnabled` and `setEnabled` we added this check to make sure we don't lose events while we figure out what's causing the SDK to shut down.
