### ISSUE TITLE
trouble with android build on flutter 3.24.3

### ISSUE THREAD

**Issue by Kibakuss** [adjust/flutter_sdk#144]
Please read the flutter migration doc https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply and update your documentation for flutter

FAILURE: Build failed with an exception.

* Where:
Build file '.../android/build.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'android'.
> Project with path ':app' could not be found in project ':adjust_sdk'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by uerceg** [comment]
Hey @Kibakuss,

Sorry for a belated reply on this ticket. Thank you for reporting this.

Did you manage to make this work in the meantime? We have checked this on our end and from what we managed to see is that on Flutter v3.24.3 and later Android app settings need to be adjusted in accordance to the advices from the link you have provided, but after those changes, Adjust Flutter plugin v5.0.2 works without any issues inside of that app.

Can you help us with the steps to reproduce the issue you described above?

Thank you in advance.
