### ISSUE TITLE
Crash  "NSInvalidArgumentException +[Adjust adid]: unrecognized selector sent to class 0x104fbb770"; (iOS)

### ISSUE THREAD

**Issue by Goodstuff4UonYT** [adjust/flutter_sdk#146]
Happens with Adjust 5.0.0 and also with the newest version 5.0.2. 
We cannot release our app version because of this.

`[  +55 ms] [AppLovinSdk] DEBUG [ALHealthEventsReporter] crash reported with code 200 and extra parameters {
[        ]     "top_main_method" = "NSInvalidArgumentException +[Adjust adid]: unrecognized selector sent to class 0x104fbb770";
[        ] }
[ +432 ms] libc++abi: terminating due to uncaught exception of type NSException
[  +51 ms] Process 489 stopped
[   +1 ms] * thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
[        ]     frame #0: 0x00000001ee9d1578 libsystem_kernel.dylib`__pthread_kill + 8
[        ] libsystem_kernel.dylib`:
[        ] ->  0x1ee9d1578 <+8>:  b.lo   0x1ee9d1598               ; <+40>
[        ]     0x1ee9d157c <+12>: pacibsp
[        ]     0x1ee9d1580 <+16>: stp    x29, x30, [sp, #-0x10]!
[        ]     0x1ee9d1584 <+20>: mov    x29, sp
[        ] Target 0: (Runner) stopped.`

Flutter:
`Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (5 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3`

**Comment by Goodstuff4UonYT** [comment]
App still crashing. Thanks for the support.

**Comment by uerceg** [comment]
Hey @Goodstuff4UonYT,

Sorry for delay on this one. Hm. Trying to access `[Adjust adid];` is SDK v4 code base. Do you see in the stack trace where is the call to that method originating from?

**Comment by Goodstuff4UonYT** [comment]
It looks to me like this is being called:

```
- (nullable NSString *)adjustUserID {
  Class Adjust = NSClassFromString(@“Adjust”);
  SEL adid = NSSelectorFromString(@“adid”);
  if (Adjust && adid) {
    id (*imp1)(id, SEL) = (id (*)(id, SEL))[Adjust methodForSelector:adid];
    NSString *adidString = nil;
    if (imp1) {
      adidString = imp1(Adjust, adid);
    }
    
    return adidString;
  }
  
  return nil;
}
```

and that by

 ```
(void)collectIntegrationsDataInBackground {
  NSString *adjustUserID = _device.adjustUserID;
  if (![QNUtils isEmptyString:adjustUserID]) {
    [self setUserProperty:@“_q_adjust_adid” value:adjustUserID];
  }
  

```

**Comment by Goodstuff4UonYT** [comment]
[Adjust]v: ClientSdk: flutter5.0.2@ios5.0.1

**Comment by uerceg** [comment]
> It looks to me like this is being called:
> 
> ```
> - (nullable NSString *)adjustUserID {
>   Class Adjust = NSClassFromString(@“Adjust”);
>   SEL adid = NSSelectorFromString(@“adid”);
>   if (Adjust && adid) {
>     id (*imp1)(id, SEL) = (id (*)(id, SEL))[Adjust methodForSelector:adid];
>     NSString *adidString = nil;
>     if (imp1) {
>       adidString = imp1(Adjust, adid);
>     }
>     
>     return adidString;
>   }
>   
>   return nil;
> }
> ```
> 
> and that by
> 
> ```
> (void)collectIntegrationsDataInBackground {
>  NSString *adjustUserID = _device.adjustUserID;
>  if (![QNUtils isEmptyString:adjustUserID]) {
>    [self setUserProperty:@“_q_adjust_adid” value:adjustUserID];
>  }
>  
> ```

Is this code from your app?

This code is referencing native iOS SDK v4 implementation of the `adid` getter that has changed and v5. That's what's causing the issue.

**Comment by Goodstuff4UonYT** [comment]
Ahh thank you. 
This is code from Qonversion sdk. I'll see if they've fixed it in the meantime and create an issue there if not :)
