### ISSUE TITLE
:app:checkDevDebugDuplicateClasses

### ISSUE THREAD

**Issue by Potato-eight** [adjust/flutter_sdk#154]
I got an error like this when building the APK, please help.

* What went wrong:
Execution failed for task ':app:checkDevDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.adjust.sdk.sig.NativeLibHelper found in modules adjust-android-signature-3.35.0.aar -> jetified-adjust-android-signature-3.35.0-runtime (com.adjust.signature:adjust-android-signature:3.35.0) and adjust-lib.aar -> jetified-adjust-lib-runtime (adjust-lib.aar)
     Duplicate class com.adjust.sdk.sig.Signer found in modules adjust-android-signature-3.35.0.aar -> jetified-adjust-android-signature-3.35.0-runtime (com.adjust.signature:adjust-android-signature:3.35.0) and adjust-lib.aar -> jetified-adjust-lib-runtime (adjust-lib.aar)
     Duplicate class com.adjust.sdk.sig.a found in modules adjust-android-signature-3.35.0.aar -> jetified-adjust-android-signature-3.35.0-runtime (com.adjust.signature:adjust-android-signature:3.35.0) and adjust-lib.aar -> jetified-adjust-lib-runtime (adjust-lib.aar)
     Duplicate class com.adjust.sdk.sig.b found in modules adjust-android-signature-3.35.0.aar -> jetified-adjust-android-signature-3.35.0-runtime (com.adjust.signature:adjust-android-signature:3.35.0) and adjust-lib.aar -> jetified-adjust-lib-runtime (adjust-lib.aar)
     Duplicate class com.adjust.sdk.sig.c found in modules adjust-android-signature-3.35.0.aar -> jetified-adjust-android-signature-3.35.0-runtime (com.adjust.signature:adjust-android-signature:3.35.0) and adjust-lib.aar -> jetified-adjust-lib-runtime (adjust-lib.aar)
     Duplicate class com.adjust.sdk.sig.d found in modules adjust-android-signature-3.35.0.aar -> jetified-adjust-android-signature-3.35.0-runtime (com.adjust.signature:adjust-android-signature:3.35.0) and adjust-lib.aar -> jetified-adjust-lib-runtime (adjust-lib.aar)
     Duplicate class com.adjust.sdk.sig.e found in modules adjust-android-signature-3.35.0.aar -> jetified-adjust-android-signature-3.35.0-runtime (com.adjust.signature:adjust-android-signature:3.35.0) and adjust-lib.aar -> jetified-adjust-lib-runtime (adjust-lib.aar)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**Comment by uerceg** [comment]
Hey @Potato-eight,

Where does the `adjust-lib.aar` that's mentioned in the logs come from? Which Adjust FSDK version are you using?

**Comment by Potato-eight** [comment]
hi @uerceg 

First, thank you for your response,
I tried to integrate the signature library from the tutorial 'https://dev.adjust.com/en/sdk/android/integrations/signature-library' and I downloaded the signature file from 'https://github.com/adjust/adjust_signature_sdk/releases/tag/v3.35.2'.

**Comment by Potato-eight** [comment]
I migrated from v3 directly to v5 without going through v4 first, it seems I didn't read the migration docs properly. Thank you @uerceg , I really appreciate your help now.

**Comment by uerceg** [comment]
No problem. I'll close the issue, but in case you have any further of follow up questions, feel free to comment / reopen.

Cheers.
