### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ghost23** [adjust/flutter_sdk#19]
Hi,

I am working on an app, where I can do most of the code in flutter/dart, but some things I have to do outside of flutter in native code. For example, because I am using certain third-party libraries, I can only access the push token outside of flutter reliably.

Now, it would be perfect for me, if you could set your dependency to the android adjust sdk as "api" instead of "implementation" in your build.gradle file. That way, I would be able to use the same Adjust SDK also in native Android code.

What do you think?

**Comment by ugi** [comment]
Hi @ghost23 

Absolutely, I think it makes sense and we'll most probably add this change to next SDK update. Will keep you posted.

Cheers

**Comment by ghost23** [comment]
wow, thanks for the quick response. Very much appreciated :)

**Comment by ghost23** [comment]
Hi. Do you guys perhaps a rough estimate, when the new release will come out with this change?

**Comment by ugi** [comment]
Hey @ghost23 

Sorry for a bit of delay, vacation time'n'stuff. We have just released [v4.22.1](https://github.com/adjust/flutter_sdk/releases/tag/v4.22.1) update with this change. Feel free to give it a shot and let us know if it worked for you. If not, feel free to comment/reopen.

Cheers

**Comment by ghost23** [comment]
works perfectly, thank you!
