### ISSUE TITLE
Not receiving deferredDeeplinkCallback

### ISSUE THREAD

**Issue by Fatimamostafa** [adjust/flutter_sdk#20]
Adjust parameter shows the log of `Url to parse` and `deeplink` parameter with a successful deeplink URL. How may I get those values? Not receiving any log at `deferredDeeplinkCallback` listener.

**Comment by ugi** [comment]
Hi @Fatimamostafa 

Is there any chance you can do the test you're talking about with SDK set to sandbox environment and log level to verbose and send us over the logs from that run? Feel free to omit any sensitive information from the logs.

Cheers

**Comment by Fatimamostafa** [comment]
> Hi @Fatimamostafa
> 
> Is there any chance you can do the test you're talking about with SDK set to sandbox environment and log level to verbose and send us over the logs from that run? Feel free to omit any sensitive information from the logs.
> 
> Cheers

Here are the screenshots. Let me know if you need any more information. 

<img width="875" alt="Screen_Shot_2020-07-25_at_1_31_45_PM" src="https://user-images.githubusercontent.com/20916180/88451949-8fad7e80-ce7c-11ea-8457-bcf967057f01.png">

<img width="621" alt="Screen Shot 2020-07-25 at 1 40 08 PM" src="https://user-images.githubusercontent.com/20916180/88451925-5d038600-ce7c-11ea-8d2b-a05dfeaf1047.png">

**Comment by ugi** [comment]
Hi,

Can't say much from that logs screenshot. If you can maybe put all logs from that run in a txt file and send me over. If you don't feel like posting that in here, you can mail it to me. 

Cheers

**Comment by Fatimamostafa** [comment]
> Hi,
> 
> Can't say much from that logs screenshot. If you can maybe put all logs from that run in a txt file and send me over. If you don't feel like posting that in here, you can mail it to me.
> 
> Cheers

Let me get back to you in mail
