### ISSUE TITLE
Adjust.track     failed

### ISSUE THREAD

**Issue by chao9267** [adjust/flutter_sdk#28]
The same code, different event creation time, the event created a long time ago failed to send, the most recently created event can be sent successfully

JSON response: {"error":"Event request failed (Ignoring event, earlier unique event tracked)"}

**Comment by uerceg** [comment]
Hi @chao9267 

This error is being reported when you try to track even which you have marked as unique in Adjust dashboard for more than one time within same installation of your app.

You can make fresh install of your app by doing this:

1. Uninstall your app from device.
2. Forget your device in testing console.
3. Install your app on device and track unique event.

You should see information that event was successfully tracked. If you try now to track the same event again, you will see the error message from above. And you're gonna see it all the time when attempting to track this event unless you perform 3 steps from above again to make fresh install of your app.

If you have any further question(s) on the topic, feel free to ping.

Cheers

**Comment by uerceg** [comment]
Hi @chao9267 

Any update in here?

Cheers
