### ISSUE TITLE
Expose `OnSessionTrackingSucceededListener` callback to easily wait until `getAdid()` returns non-`null` ID

### ISSUE THREAD

**Issue by tp** [adjust/flutter_sdk#34]
Hey,

we discovered a race-condition in our app which was driven by the fact that initial calls to `getAdid()` (with a fresh install), after "going online" with `setOfflineMode(false)`, return `null` initially.

Only if one calls this again a few seconds later will it return an actual string identifier.

In an issue for the native Android SDK (https://github.com/adjust/android_sdk/issues/454), you suggest to wait for a [session event callback](https://github.com/adjust/android_sdk#af-session-event-callbacks).

Unfortunately this does not seem to be exposed via the Flutter SDK yet. Would you be willing to add this?

Our current workaround is to poll the `getAdid()` function until it returns the first value.

Alternatively I could also see the behavior of `getAdid()` to be changed to have the Future resolve only after an ID has been received. This might of course take a long time and might be unexpected to callers (so they should never put it into the user's path).

**Comment by uerceg** [comment]
Hi @tp

Thanks for detailed description. We actually do have these exposed in Flutter SDK:

- https://github.com/adjust/flutter_sdk/blob/master/lib/adjust_session_success.dart
- https://github.com/adjust/flutter_sdk/blob/master/lib/adjust_session_failure.dart

And here's an example of how you can set them in your app:

- https://github.com/adjust/flutter_sdk/blob/master/example/lib/main.dart#L135
- https://github.com/adjust/flutter_sdk/blob/master/example/lib/main.dart#L152

Let me know if this worked for you, in theory it should.

Cheers

**Comment by tp** [comment]
Thank you so much for the detailed respponse.

I was looking on the wrong class (`Adjust` instead of the `config`).

We will start using this in ~1 week. If anything comes up during implementation I will reach out again.

**Comment by tp** [comment]
@uerceg, I am looking currently at a reliable way to get the Adid on a second app start (so I thought it would be already persisted locally then).

In my testing: 
-`Adjust.getAdid()` resolves to `null`
- callback set for `sessionSuccessCallback` is never invoked
- callback set for `attributionCallback` is never invoked

The event callbacks (e.g. `eventSuccessCallback`) work just fine though.

Is this in any way expected?

One "specialty" in our code-base is that we always start out with calling `Adjust.setOfflineMode(true)` before calling `Adjust.start(config)`.

Only after we have confirmed that we have tracking consent do we call `Adjust.setOfflineMode(false)`.

So while it would be nice to get the `Adid` before sending an event (or using an delayed call to `getAdid()` which also works then), this isn't a deal-breaker for us overall.
