### ISSUE TITLE
Bump and implement native SDKs to Android 4.26.+ and iOS 4.25.+

### ISSUE THREAD

**Issue by Sese-Schneider** [adjust/flutter_sdk#36]
To be able to use the new features of the Adjust native SDKs, the flutter sdk implementation has to be bumped to the newest versions / the new features have to be implemented.

#### iOS:
- **Added Facebook audience network ad revenue source string.**
- **Added support for Apple Search Ads attribution with usage of AdServices.framework.**
- Added appTrackingAuthorizationStatus getter to Adjust instance to be able to get current app tracking status.
- Added improved measurement consent management and third party sharing system.
- Added possibility to get cost data information in attribution callback.
- Added setNeedsCost: method to ADJConfig to indicate if cost data is needed in attribution callback (by default cost data will not be part of attribution callback if not enabled with this setter method).
- Enabled position independent code generation.
- Improved logging.
- Addressed Xcode warnings regarding deprecated API usage.
- Removed some obsolete and unused API.
- Replaced malloc with more secure calloc calls (https://github.com/adjust/ios_sdk/pull/432).

#### Android:
- Added Facebook audience network ad revenue source string.
- Changed minimum supported API version to 17 for webbridge, to avoid insecure JavaScript potential injections on lower API - 
- Moved reading of install referrer details to background thread after service connection establishes.
- Added improved measurement consent management and third party sharing system.
- Added possibility to get cost data information in attribution callback.
- Added setNeedsCost(boolean) method to AdjustConfig to indicate if cost data is needed in attribution callback (by default cost data will not be part of attribution callback if not enabled with this setter method).
- Added setPreinstallTrackingEnabled method to adjust_config.js to allow enabling of preintall tracking from web bridge plugin.
- Switched from usage of deprecated getNetworkType() method to getDataNetworkType() on devices running Android 11 or later.

**Comment by uerceg** [comment]
Hi @Sese-Schneider 

Yep, we're rolling out one more iOS SDK update right now and after that one's out, we're starting with non native SDK updates to pick up all the latest native features as well.

Will keep you posted.

**Comment by uerceg** [comment]
Hey @Sese-Schneider,

We have just released [v4.26.0](https://github.com/adjust/flutter_sdk/releases/tag/v4.26.0) update where all current native features have been added to Flutter SDK as well.

Thanks for your patience!

Cheers
