### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [adjust/flutter_sdk#41]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:adjust_sdk`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by uerceg** [comment]
Hi @IchordeDionysos 

Thanks for suggestion! I was skimming though this page and noticed [SDK constraints](https://dart.dev/null-safety/migration-guide#sdk-constraints) section. Does this mean that upon migrating plugin to this approach, our plugin will only be usable for those using Flutter 2.12 or above?

**Comment by IchordeDionysos** [comment]
Hey @uerceg, 

Yes the upgrade to null-safety is usually coupled with a major version upgrade as it's a breaking change.

If you increase the version constraints now and publish the package to pub.dev the new version would be marked as a Preview release and gets automatically promoted to be a stable release once the required Dart version is released to stable.
See also this article: https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

Meaning you can safely publish the migration to null safety now without breaking anyone yet.

**Comment by IchordeDionysos** [comment]
@uerceg ah to clarify the SDK constraint is for the Dart version NOT the Flutter version.

The Flutter and the Dart version usually get released to stable at the same time. Probably March 3rd (Flutter event).

And anyone with the next stable version of Flutter/Dart will be able to use the package with the update version constraint.

**Comment by IchordeDionysos** [comment]
@uerceg the new Dart version was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by uerceg** [comment]
Hey @IchordeDionysos 

Thanks for the update! We're gonna check this topic and try to add null safety to be part of our next release. No exact on ETA on this one right now, but will keep you posted.

Cheers

**Comment by IchordeDionysos** [comment]
@uerceg any news yet if this can make the next release? 🤔 
Adjust ist one of the few last libraries blocking the null-safety migration on our end.

**Comment by uerceg** [comment]
Hi @IchordeDionysos,

Yes, we are getting close to have next Flutter SDK release ready which supports null safety. Still no firm release date on our end, but hopefully within next two weeks.

**Comment by kjawadDeveloper1** [comment]
Any update

**Comment by uerceg** [comment]
Sorry for delay, we had some internal pushbacks which made us postpone this release a bit. Will update as soon as we get new clear ETA.

**Comment by melikhanHosdogdu** [comment]
Is there any update?

**Comment by kuncieid** [comment]
Hi @uerceg , any update on this? Adjust sdk is now the last blocker for our team to migrate to null-safety :(

**Comment by ryanheise** [comment]
> Yes, we are getting close to have next Flutter SDK release ready which supports null safety. Still no firm release date on our end, but hopefully within next two weeks.

I will be happy to contribute a pull request if that's OK. I would expect 1-2 days work max (I realise the Adjust team may be working on some other changes which could be delaying the release, but this pull request will focus just on the Flutter 2 changes which are urgent and blocking.)

**Comment by ryanheise** [comment]
Edit: Cool:  #43 is already contributed :-)

**Comment by uerceg** [comment]
Hey guys,

Yeah, sorry for delay, we had some other more urgent things in backlog to push live and we are back on this topic as of today. Yes, we're pretty much building on top of #43 which is amazing contribution. Will keep you posted on progress.

**Comment by kikuchy** [comment]
I'm waiting for the progress.

**Comment by thainguyen-fika** [comment]
Keep waiting for your progress. It's been a month now.

**Comment by ryanheise** [comment]
The Flutter team encourages (encourage"d") all plugin authors to migrate their plugins to Flutter 2 _before_ the big announcement and release date of Flutter 2 (which has now elapsed). See this call for action from last year:

https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a

asking developers to start preparing for the Flutter 2 release back in November 2020.

@uerceg The pull request #43 is working well (we are using a direct git dependency), so please consider doing a priority release of this pull request as is. If the reason for the delay is to add other features or fixes in the same release, please do it as two separate releases, fist publishing #43 so that customers aren't blocked, and then doing a follow up release with the stuff that's taking months longer.

**Comment by uerceg** [comment]
Hey guys.

Mentioned in original null safety PR, but one more time in here: thank you all for your patience and one more time sorry for the delay on this topic. We have just released Flutter SDK v4.29.0 (https://github.com/adjust/flutter_sdk/releases/tag/v4.29.0) which adds support for null safety. Please, give it a shot and in case you encounter any issue or have any further questions about it, please feel free to comment / reopen.

Cheers.

**Comment by ryanheise** [comment]
Just a note on version numbers, Flutter's [null safety migration guide](https://dart.dev/null-safety/migration-guide#package-version) indicates that null safety migrations are breaking changes and get a major version bump:

> Package version
> 
> Update the version of the package to indicate a breaking change:
> 
> * If your package is already at 1.0.0 or greater, increase the major version. For example, if the previous version is 2.3.2, the new version is 3.0.0.

**Comment by uerceg** [comment]
Hey @ryanheise,

Thanks for the note. We did saw that, but seemed like it was not a hard dependency. We do have our own version logic which we are keeping for years amongst all of our SDKs, thus we didn't go with that advice.

In way how this latest release is implemented (4.29.0), does it cause some problems (other than us not following the versioning advice for null safety)?

**Comment by ryanheise** [comment]
Increasing the min SDK version constraint is a breaking change, particularly for apps that have for one reason or another pinned to an older SDK version.

Although I think there was some new logic added to `pub` to prevent a package version from upgrading if that upgrade wasn't compatible with their current SDK, and this would on the surface seem to be a way to solve this problem. However, I'm not sure when this was added, and whether developers running old versions of the pub tool would still be vulnerable to having an automatic upgrade to this breaking change. In any case, publishing is permanent so if a developer does run into this issue and needs to stick to the old version, they could use a version spec of `'4.28.0` in their `pubspec.yaml` (without the caret).
