### ISSUE TITLE
App not sending install tracking in Production, works in Sandbox

### ISSUE THREAD

**Issue by kuncieid** [adjust/flutter_sdk#47]
Environment:
- Flutter v1.22.6
- Flutter Adjust sdk v4.28.0
- Adjust has uninstall event add-on and sdk signature activated
- build.gradle dependencies version
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.android.gms:play-services-analytics:17.0.0'
    implementation 'com.android.installreferrer:installreferrer:1.0'
}
- AppSealing v2.22.0

On local, we can track install data to Sandbox and Production well.
But on after the release workflow in CI/CD, Adjust not sending install data to production.

Code to generate the release build below : 
flutter build appbundle --release --no-shrink --build-name=$(yq e .versionProd pubspec.yaml)  --build-number=$PROJECT_BUILD_NUMBER  --obfuscate --split-debug-info=obfuscate/symbols

Our hypothesis that the obfuscate symbol here creating problem for Adjust SDK to work properly.
On https://github.com/adjust/flutter_sdk, we read there is step for proguard to exclude Adjust SDK from being obfuscated, but we don't find specific instruction for flutter obfuscate. 

Please confirm our hypothesis or if there's other watchout for the release build.

**Comment by kuncieid** [comment]
Hi @uerceg thanks for replying. We try to remove the obfuscate flag, but still the release app not sending data to Adjust.
It's sending data if we run on flutter debug mode (both to sandbox and production), but stop sending data when we build with flutter build release flag (not sending to sandbox and production).

Any other things we need to do to make the release mode work?

**Comment by uerceg** [comment]
Hm. That's pretty weird. Can you please run **release** build of your app and have our SDK set to **sandbox** mode and log level to **verbose**. Then simply install app and run it, pick up all the app logs from that run and send them over. If logs are not something you would be wiling to share in here, feel free to email me (you can find my email in my profile page).

**Comment by kuncieid** [comment]
hi @uerceg , it seems there's problem with adjust secret that we store in encrypted variables CI/CD. We are able to send data to Adjust with release mode on local (quite troublesome to do proper build in local so not checking this at first). Therefore I'm closing this issue. Thank you for the suggestion!

**Comment by firatcetiner** [comment]
@kuncieid So this issue isn't related with using `--obfuscate` for `flutter build`? 

@uerceg Do you have enough information to tell us it won't break the core functionality of Adjust SDK if we use --obfuscate flag? Currently, --obfuscate flag only performs obfuscation on pure Dart code and we don't intent further obfuscate the native code using Proguard. What do you think? Can we use --obfuscate flag without hesitations?

**Comment by uerceg** [comment]
Hi @firatcetiner 

I think that it should be fine to use that flag. So far we never had any issue reported if that flag was used (I'd assume that Flutter devs probably use that in their apps). Nevertheless, I would advise to double check if things work with app build made with that flag - just run tests to see if things are working fine on Adjust end to be on a safe side.
