### ISSUE TITLE
Crashed on iOS devices

### ISSUE THREAD

**Issue by iscojin** [adjust/flutter_sdk#48]
Hello, there!

Currently I am using adjust_sdk package to implement the adjust sdk into our flutter application.

It is working well on android.

But on some iOS devices, just crashed.
iOS 14.2 (iPhone11)

Sdk is not comfortable for iOS 14.2?

Looking forward to hearing from anyone to fix this issue.

Thanks

**Comment by uerceg** [comment]
Hi @iscojin 

SDK should support and work well on 14.2. Can you share more details about the crash which happens? Can we get the stack trace and/or more details about devices from Crashylitcs (or some other) report you're checking?

**Comment by iscojin** [comment]
Hi, @uerceg 
My app have splash page while loading some data. Then in home page, I initialize the adjust sdk.

But for some iOS devices, just crash when open the app. Our users can show the only splash page then crash.
I need to fix this issue asap. Cuz our app lost many users now.

Thanks

**Comment by uerceg** [comment]
@iscojin 

Thanks for a bit more details, but still like I mentioned in my previous comment, we need to see crash stack trace to figure first what caused the crash and then to try to see how to fix that if our SDK is causing the crash.

**Comment by iscojin** [comment]
@uerceg 

I will do my best to get crash stack trace cuz I have no this device.

**Comment by uerceg** [comment]
@iscojin 

Maybe a thing you can check next to trying to get stack trace would be if you're having `AdServices.framework` linked in your iOS app Xcode project. And if yes, is it set to be `Required` or `Optional`?

**Comment by iscojin** [comment]
Here is the screenshot to show the frameworks I added

<img width="626" alt="Screenshot 2021-04-22 at 12 17 48 PM" src="https://user-images.githubusercontent.com/60736395/115705940-0c667e00-a365-11eb-87a4-17e5b00ca341.png">

**Comment by iscojin** [comment]
> Here is the screenshot to show the frameworks I added
> 
> <img alt="Screenshot 2021-04-22 at 12 17 48 PM" width="626" src="https://user-images.githubusercontent.com/60736395/115705940-0c667e00-a365-11eb-87a4-17e5b00ca341.png">

If something wrong with this one, please guide me.
Cuz adjust is first time to me.

**Comment by uerceg** [comment]
Can you send screenshot of frameworks from `Build Phases -> Link Binary With Libraries` section?

**Comment by iscojin** [comment]
Here.

<img width="601" alt="Screenshot 2021-04-22 at 12 22 30 PM" src="https://user-images.githubusercontent.com/60736395/115706433-8bf44d00-a365-11eb-862e-aaf14edd35e6.png">

**Comment by uerceg** [comment]
Yep, that is most probably the issue. Feel free to set all of these to `Optional`:

- `AdSupport.framework`
- `CoreTelephony.framework`
- `StoreKit.framework`
- `iAd.framework`
- `AppTrackingTransparency.framework`
- `AdServices.framework`

In theory most crucial ones to put to `Optional` are `AdServices.framework` and `AppTrackingTransparency.framework` which Apple introduced in iOS 14.x versions. If those are set as `Required`, they will crash your app on any device which runs iOS version below mentioned iOS 14.x. If you added all those frameworks just because of Adjust SDK, then feel free to set them all to `Optional` since our SDK doesn't depend directly to any of those.

This is also suggested in our [README chapter](https://github.com/adjust/flutter_sdk/#qs-ios-frameworks) about additional iOS frameworks.

**Comment by iscojin** [comment]
Thanks for your guidance.

If I set those all as optional, I can still track the event with adjust sdk?

**Comment by uerceg** [comment]
Absolutely. All of those frameworks provide some additional functionalities which our SDK might take advantage of if you have them linked with your app (purpose of each one is explained in that above mentioned chapter). But install / session / event tracking has nothing to do with these frameworks, it's core functionality of the SDK.

**Comment by iscojin** [comment]
Thanks, 

then one more question
How can I set the revenue tracking?

Should I set revenue when track the only purchase event?

**Comment by iscojin** [comment]
When set the revenue, this api has two params.

First one is num and second is currency.
Please can you explain me what is the first param

**Comment by uerceg** [comment]
Probably yes. Usually you would track event when purchase in your app is completed and then **AdjustEvent** class offers you a way to attach revenue and currency for that purchase to the event and then track it.

You can check how that's done in [example app](https://github.com/adjust/flutter_sdk/blob/master/example/lib/util.dart#L70-L74).

Feel free to ignore `callbackId` and `transactionId` fields if you don't need them.

**Comment by uerceg** [comment]
You also have all of this explained in our [README](https://github.com/adjust/flutter_sdk#et-revenue).

**Comment by iscojin** [comment]
Much appreciated for your help.

I am building new iOS version so once check it if issue fixed I will close this thread here.

Thanks

**Comment by uerceg** [comment]
Sounds great. Keep us posted. 🤞

**Comment by iscojin** [comment]
@uerceg 

Thanks for your help, it was really helpful for me and for my company. Now I am closing this issue.

Keep in touch! :)

**Comment by iscojin** [comment]
> Yep, that is most probably the issue. Feel free to set all of these to `Optional`:
> 
> * `AdSupport.framework`
> * `CoreTelephony.framework`
> * `StoreKit.framework`
> * `iAd.framework`
> * `AppTrackingTransparency.framework`
> * `AdServices.framework`
> 
> In theory most crucial ones to put to `Optional` are `AdServices.framework` and `AppTrackingTransparency.framework` which Apple introduced in iOS 14.x versions. If those are set as `Required`, they will crash your app on any device which runs iOS version below mentioned iOS 14.x. If you added all those frameworks just because of Adjust SDK, then feel free to set them all to `Optional` since our SDK doesn't depend directly to any of those.
> 
> This is also suggested in our [README chapter](https://github.com/adjust/flutter_sdk/#qs-ios-frameworks) about additional iOS frameworks.

Issue fixed properly, thanks!
