### ISSUE TITLE
Tracking Unistall ios

### ISSUE THREAD

**Issue by ThangNguyen91** [adjust/flutter_sdk#49]
I went through the document here and followed it
[https://help.adjust.com/en/article/uninstalls-reinstalls]
in android it works fine. But on ios, i am using both p8 and p12 on firebase but its not working i tried on testflight and also build ipa. Status unchanged, sent token firebase to adjust. 
Expected behavior: Adjust tracked uninstall app on Ios

**Comment by uerceg** [comment]
Hi @ThangNguyen91 

Uninstall detection in iOS doesn't work with Firebase. In iOS, you need to pass APNs token, not FCM.

**Comment by ThangNguyen91** [comment]
Thanks you for support. I'll try again.

**Comment by ThangNguyen91** [comment]
I sent APNs token but it still doesn't work.

**Comment by ThangNguyen91** [comment]
> Hi @ThangNguyen91
> 
> Uninstall detection in iOS doesn't work with Firebase. In iOS, you need to pass APNs token, not FCM.

I sent APNs token but it still doesn't work.

**Comment by uerceg** [comment]
@ThangNguyen91 

Sorry for delay in replying. Any luck in the meantime? If not, I'd suggest contacting either your dedicated account manager (if you have one) or support@adjust.com. Troubleshooting this topic is a bit complex and lead by our support team, so definitely faster and more efficient if you reach out to them directly.

Cheers
