### ISSUE TITLE
Android build FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [adjust/flutter_sdk#50]
When trying to build on Android using `flutter run`, I am running into the following issue using `adjust_sdk: ^4.28.0`:

```
Building plugin adjust_sdk...
Running Gradle task 'assembleAarRelease'...


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'AppData\Local\Pub\Cache\hosted\pub.dartlang.org\adjust_sdk-4.28.0\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin adjust_sdk could not be built due to the issue above.
```

I was not able to solve this by including the `sdk.dir` property in the cached package nor the SDK root variable.

**Comment by creativecreatorormaybenot** [comment]
What confuses me is why the `assembleAarRelease` Gradle task is even run. After I fixed a totally unrelated issue Gradle build issue that appeared during assemble debug, this task was not executed anymore.

**Comment by chillbrodev** [comment]
Any resolution on this? I am stumped by this issue.  @creativecreatorormaybenot what issue did you fix?

**Comment by creativecreatorormaybenot** [comment]
unrelated (nothing to do with Adjust).

**Comment by deicon** [comment]
SAme here. Breaks my build since 3 days. Had to remove adjust sdk from code.

**Comment by deicon** [comment]
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-DE)
    • Flutter version 2.2.2 at dev/tools/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

**Comment by uerceg** [comment]
Hey guys,

Sorry for a delay in responding to this one. We weren't able to reproduce this on our end. 🤔 Can you just for sake of consistency check the latest (v4.29.1) version of our plugin and let us know if you're still facing these build errors?

**Comment by uerceg** [comment]
Just following up in here ☝️.

**Comment by creativecreatorormaybenot** [comment]
As I said initially, I was not able to reproduce this without the unrelated build issues.

**Comment by uerceg** [comment]
We were giving a shot to reproduce this issue, but unfortunately unable to reproduce it with any of the `flutter` versions we tried. Latest attempt we did with:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.62.3)
[✓] Connected device (3 available)
• No issues found!
```

Really not sure how to address this without ability to reproduce it. Simple Googling for the error you are facing with seems like it might be related to [Gradle version](https://github.com/mogol/flutter_secure_storage/issues/220) you might be using. Did you maybe give that a shot?
