### ISSUE TITLE
Compile error when try to run IOS app

### ISSUE THREAD

**Issue by bironader** [adjust/flutter_sdk#58]
I face this issue when I build IOS app integrated with adjust flutter SDK 

<img width="1236" alt="Screen Shot 2021-09-09 at 2 41 21 PM" src="https://user-images.githubusercontent.com/20532507/132687672-fa9bbafc-0c86-4f0f-a269-aae9edc4ccab.png">

refer to this [pr](https://github.com/adjust/ios_sdk/pull/547) need to be applied also in IOS flutter SDK

**Comment by uerceg** [comment]
Hi @bironader 

Yep, needs to be picked up. Will be there with next Flutter SDK update. Will keep you posted.

**Comment by bironader** [comment]
Hi @uerceg 
Thanks for your fast reply 
I fix it in this [pr](https://github.com/adjust/flutter_sdk/issues/58)

**Comment by HyperJames** [comment]
@uerceg / @bironader - is there any update on when this PR will be merged please?

**Comment by uerceg** [comment]
Coming soon. A day or two. Will keep you posted.

**Comment by uerceg** [comment]
Actually, a bit sooner. We just released [v4.29.1](https://github.com/adjust/flutter_sdk/releases/tag/v4.29.1) which should hopefully address this issue. In case issue is not resolved with this version, feel free to comment / reopen. Cheers guys.
