### ISSUE TITLE
com.google.android.gms:play-services-analytics deprecated

### ISSUE THREAD

**Issue by rbresjer** [adjust/flutter_sdk#63]
Hi,

I just integrated the Adjust SDK in our Flutter app. I saw we need to add `com.google.android.gms:play-services-analytics` to the build.gradle and that Adjust doesn't care about a specific version. I googled what the latest version is and saw that the package is [deprecated](https://developers.google.com/android/guides/setup#list-dependencies) in favor of Firebase Analytics.

In our project we do use Firebase Analytics. Is this package required then?

Thanks,
Rutger

**Comment by uerceg** [comment]
Hi @rbresjer,

Sorry for delay on this one. Yeah, this is good point and we should also update our README regarding this. `play-services-analytics` is the package which used to contain API for reading Google Advertising ID, but nowadays that API got extracted into smaller package which is called [`ads-identifier`](https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads-identifier?repo=google). So feel free to import the latest version of that package and it should be fine.

In case you have any further questions on this topic, feel free to ping / reopen the issue.

Cheers!
