### ISSUE TITLE
apk not found in build/app/outputs/apk after adding adjust-sdk

### ISSUE THREAD

**Issue by xiejinpeng007** [adjust/flutter_sdk#65]
Normally , the apk will be generate both in folder `build/app/outputs/apk` and `build/app/outpus/flutter-apk`.
But after adding adjust-sdk (4.29.1) , folder `build/app/outputs/apk` is not generated.
Is this a bug from adjust-sdk?
<img width="319" alt="截屏2021-10-19 下午2 14 05" src="https://user-images.githubusercontent.com/12725289/137853852-d0ee91e0-d7c2-4789-a9f0-7a1b31de46be.png">

**Comment by uerceg** [comment]
Hi @xiejinpeng007,

In theory, it shouldn't be related to our SDK. What determines folder structure inside of the build directory in Android is usually Gradle version. Did you maybe update your Gradle version before you started to notice that output of your APK is on different location?

**Comment by uerceg** [comment]
Closing this one since it doesn't appear to be SDK related issue, but in case you have further questions on this topic, feel free to ping in here. Cheers!
