### ISSUE TITLE
App closes when opening cameras and initializing external SDKs

### ISSUE THREAD

**Issue by Gustavo0Henrick** [adjust/flutter_sdk#67]
The Adjust SDK is preventing some important functions from working in the Uzzo Pay app. QR Code Readers and Barcode Scanner are being prevented from accessing the device's native camera and also from accessing remote machine learning libraries. The app also has an integration with the Zendesk SDK and when we implement the Adjust SDK, Zendesk crashes and cannot run. In all the cases we've identified, there's a problem initializing the functions and the app closes. The packages and SDKs installed in the application were working normally and started to fail after the implementation of the Adjust SDK.

- **SDK error**

`I/TetheringManager( 1006): registerTetheringEventCallback:com.therabank.uzzo
W/.therabank.uzz( 1006): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/.therabank.uzz( 1006): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/FloatingActionButton( 1006): Setting a custom background is not supported.
D/AndroidRuntime( 1006): Shutting down VM
E/AndroidRuntime( 1006): FATAL EXCEPTION: main
E/AndroidRuntime( 1006): Process: com.therabank.uzzo, PID: 1006
E/AndroidRuntime( 1006): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.therabank.uzzo/zendesk.support.guide.HelpCenterActivity}: java.lang.IllegalArgumentException: Unable to create call adapter for interface m.g
E/AndroidRuntime( 1006):     for method SdkSettingsService.getSettings
E/AndroidRuntime( 1006): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/AndroidRuntime( 1006): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime( 1006): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime( 1006): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 1006): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 1006): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 1006): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 1006): 	at android.os.Looper.loop(Looper.java:223)`

- **Error with cameras**

`W/Gralloc4( 1843): allocator 3.x is not supported
D/q       ( 1843): resume()
D/l       ( 1843): Opening camera
W/CameraBase( 1843): An error occurred while connecting to camera 0: Status(-8, EX_SERVICE_SPECIFIC): '1: validateClientPermissionsLocked:1165: Caller "com.therabank.uzzo" (PID 10161, UID 1843) cannot open camera "0" without camera permission'
E/l       ( 1843): Failed to open camera
E/l       ( 1843): java.lang.RuntimeException: Fail to connect to camera service
E/l       ( 1843): 	at android.hardware.Camera.<init>(Camera.java:557)
E/l       ( 1843): 	at android.hardware.Camera.open(Camera.java:402)
E/l       ( 1843): 	at d.e.e.s.a.m.b.a.b(:83)
E/l       ( 1843): 	at com.journeyapps.barcodescanner.M.n.l(:142)
E/l       ( 1843): 	at com.journeyapps.barcodescanner.M.h.run(:200)
E/l       ( 1843): 	at android.os.Handler.handleCallback(Handler.java:938)
E/l       ( 1843): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/l       ( 1843): 	at android.os.Looper.loop(Looper.java:223)
E/l       ( 1843): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/l       ( 1843): Configuring camera
E/l       ( 1843): Failed to configure camera
E/l       ( 1843): java.lang.RuntimeException: Camera not open
E/l       ( 1843): 	at com.journeyapps.barcodescanner.M.n.e(:161)
E/l       ( 1843): 	at com.journeyapps.barcodescanner.M.i.run(:213)
E/l       ( 1843): 	at android.os.Handler.handleCallback(Handler.java:938)
E/l       ( 1843): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/l       ( 1843): 	at android.os.Looper.loop(Looper.java:223)
E/l       ( 1843): 	at com.journeyapps.barcodescanner.M.i.run(:213)
E/l       ( 1843): 	at android.os.Handler.handleCallback(Handler.java:938)
E/l       ( 1843): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/l       ( 1843): 	at android.os.Looper.loop(Looper.java:223)
E/l       ( 1843): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/q       ( 1843): pause()
D/l       ( 1843): Closing camera
D/q       ( 1843): resume()
D/l       ( 1843): Opening camera
D/l       ( 1843): Configuring camera
I/n       ( 1843): Camera Display Orientation: 90
I/n       ( 1843): Initial camera parameters: preview-size=1280x720;video-size=1280x720;preferred-preview-size-for-video=1280x720;preview-size-values=640x480,352x288,320x240,176x144,1280x720,1280x960;video-size-values=640x480,352x288,320x240,176x144,1280x720;preview-format=yuv420sp;preview-format-values=rgba8888,yuv420p,yuv420sp;preview-frame-rate=30;preview-fps-range=5000,30000;preview-fps-range-values=(5000,30000),(15000,30000),(15000,15000),(30000,30000);preview-frame-rate-values=30,15;picture-size=640x480;picture-size-values=640x480,352x288,320x240,176x144,1280x720,1280x960;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,160x120,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,daylight,shade;effect=none;effect-values=none;antibanding=auto;antibanding-values=off,auto;scene-mode=auto;scene-mode-values=auto,;focus-mode=fixed;focus-mode-values=fixed;max-num-focus-areas=0;focus-areas=(0,0,0,0,0);focal-length=5;horizontal-view-angle=35.4893;vertical-view-angle=26.9915;exposure-compensation=0;max-exposure-compensation=9;min-exposure-compensation=-9;exposure-compensation-step=0.333333;auto-exposure-lock-supported=false;auto-whitebalance-lock-supported=false;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,109,118,127,136,145,154,163,172,181,190,200,209,218,227,236,245,254,263,272,281,290,299,309,318,327,336,345,354,363,372,381,390,399,409,418,427,436,445,454,463,472,481,490,499,509,518,527,536,545,554,563,572,581,590,599,609,618,627,636,645,654,663,672,681,690,699,709,718,727,736,745,754,763,772,781,790,799,809,818,827,836,845,854,863,872,881,890,899,909,918,927,936,945,954,963,972,981,990,999;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=0;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=false
I/CameraConfiguration( 1843): Requesting focus mode value from among: [auto]
I/CameraConfiguration( 1843): Supported focus mode values: [fixed]
I/CameraConfiguration( 1843): No supported values match
I/CameraConfiguration( 1843): Requesting focus mode value from among: [macro, edof]
I/CameraConfiguration( 1843): Supported focus mode values: [fixed]
I/CameraConfiguration( 1843): No supported values match
I/CameraConfiguration( 1843): Requesting flash mode value from among: [off]
I/CameraConfiguration( 1843): Supported flash mode values: null
I/CameraConfiguration( 1843): No supported values match
I/y       ( 1843): Viewfinder size: 2504x1440
I/y       ( 1843): Preview in order of preference: [1280x720, 1280x960, 640x480, 352x288, 320x240, 176x144]
I/n       ( 1843): Final camera parameters: video-size=1280x720;preferred-preview-size-for-video=1280x720;preview-size-values=640x480,352x288,320x240,176x144,1280x720,1280x960;video-size-values=640x480,352x288,320x240,176x144,1280x720;preview-format=yuv420sp;preview-format-values=rgba8888,yuv420p,yuv420sp;preview-frame-rate=30;preview-fps-range=5000,30000;preview-fps-range-values=(5000,30000),(15000,30000),(15000,15000),(30000,30000);preview-frame-rate-values=30,15;picture-size=640x480;picture-size-values=640x480,352x288,320x240,176x144,1280x720,1280x960;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,160x120,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,daylight,shade;effect=none;effect-values=none;antibanding=auto;antibanding-values=off,auto;scene-mode=auto;scene-mode-values=auto,;focus-mode=fixed;focus-mode-values=fixed;max-num-focus-areas=0;focus-areas=(0,0,0,0,0);focal-length=5;horizontal-view-angle=35.4893;vertical-view-angle=26.9915;exposure-compensation=0;max-exposure-compensation=9;min-exposure-compensation=-9;exposure-compensation-step=0.333333;auto-exposure-lock-supported=false;auto-whitebalance-lock-supported=false;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,109,118,127,136,145,154,163,172,181,190,200,209,218,227,236,245,254,263,272,281,290,299,309,318,327,336,345,354,363,372,381,390,399,409,418,427,436,445,454,463,472,481,490,499,509,518,527,536,545,554,563,572,581,590,599,609,618,627,636,645,654,663,672,681,690,699,709,718,727,736,745,754,763,772,781,790,799,809,818,827,836,845,854,863,872,881,890,899,909,918,927,936,945,954,963,972,981,990,999;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=0;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=false;preview-size=1280x720
I/s       ( 1843): Preview: 720x1280; Scaled: 1440x2560; Want: 1440x2504
I/q       ( 1843): Starting preview
D/AndroidRuntime( 1843): Shutting down VM
D/l       ( 1843): Starting preview
E/AndroidRuntime( 1843): FATAL EXCEPTION: main
E/AndroidRuntime( 1843): Process: com.therabank.uzzo, PID: 1843
E/AndroidRuntime( 1843): java.lang.RuntimeException: java.lang.NoSuchMethodException: d.e.e.e.values []
E/AndroidRuntime( 1843): 	at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime( 1843): 	at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime( 1843): 	at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime( 1843): 	at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime( 1843): 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime( 1843): 	at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime( 1843): 	at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime( 1843): 	at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
E/AndroidRuntime( 1843): 	at java.util.EnumMap.<init>(EnumMap.java:138)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.B.a(:38)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.BarcodeView.P(:119)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.BarcodeView.V(:178)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.BarcodeView.E(:188)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.q.K(:787)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.q.L(:530)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.q.D(:474)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.q.d(:60)
E/AndroidRuntime( 1843): 	at com.journeyapps.barcodescanner.m.handleMessage(:202)
E/AndroidRuntime( 1843): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1843): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 1843): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 1843): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1843): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 1843): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 1843): Caused by: java.lang.NoSuchMethodException: d.e.e.e.values []
E/AndroidRuntime( 1843): 	at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime( 1843): 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime( 1843): 	at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime( 1843): 	... 23 more
I/g       ( 1843): Current focus mode 'fixed'; use auto focus? false
I/.therabank.uzz( 1843): Background young concurrent copying GC freed 39951(2048KB) AllocSpace objects, 18(872KB) LOS objects, 45% free, 3476KB/6425KB, paused 10.516ms total 51.273ms
D/TransportRuntime.SQLiteEventStore( 1843): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler( 1843): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-2063191763 in 1000ms(Backend next call timestamp 1636053639622). Attempt 1
I/Process ( 1843): Sending signal. PID: 1843 SIG: 9
Lost connection to device.
Exited (sigterm)
`

**Comment by uerceg** [comment]
Hi @Gustavo0Henrick 

Thanks for the report. Stack traces you sent are showing that first crash seems to have something to do with Zendesk SDK, not exactly sure what is causing the second one. I do understand what you described (that you are starting to see these when you add Adjust SDK into your app), but unfortunately I am not really sure how can we help you in here because Adjust SDK execution doesn't seem to be causing any of these exceptions. There is not much information which might help us to figure out what exactly is happening in here.

**Comment by uerceg** [comment]
Closing this one, but in case you end up having any new stack trace which is pointing out at Adjust API in there, please feel free to share it with us.
