### ISSUE TITLE
Need OAID support in Flutter Plugin

### ISSUE THREAD

**Issue by rpsnaik** [adjust/flutter_sdk#68]
I am trying to implement Adjust SDK with Huawei Store and as per documentations from Huawei team i need to capture OAID but i seen in the Flutter plugin source code that the OAID support is not there in plugin

Docs for reference -
https://github.com/adjust/android_sdk/blob/master/doc/english/plugins/oaid.md
https://developer.huawei.com/consumer/en/doc/distribution/promotion/adjust-0000001121931660

**Comment by uerceg** [comment]
Hey @rpsnaik 

Sorry for delay on this one. We will flag this as a feature request to our product team. In the meantime, if you're willing to, you can try to add this feature natively. You can in theory simply try to import OAID plugin in your Gradle dependency list and then navigate into your native Java or Kotlin app code to add [call to enable OAID reading](https://github.com/adjust/android_sdk/blob/master/doc/english/plugins/oaid.md#use-the-plugin) in there and that should do the trick.

In case you're willing to give this a shot, let us know did it work for you and feel free to ping in here in case you have any further questions or need any further help.

**Comment by uerceg** [comment]
Hi @rpsnaik 

Did you maybe managed to try the suggested approach from above?

**Comment by rpsnaik** [comment]
Hey @uerceg I tried adding the 
```
AdjustOaid.readOaid(applicationContext);
Adjust.onCreate(config);
```
but i came across some error says to add MSA SDK to app
and when i seen the MSA website to download the SDK
the SDK requested for some Corporate agreements and some documents, So i am struck at that place

Is MSA SDK necessary to read OAID from device ?

**Comment by uerceg** [comment]
Hey @rpsnaik 

And sorry for delay. Yes, MSA SDK is really needed to be added to your app and yes, way of obtaining it from the official website is not really super straightforward, but it is something you'd need to do in order to get it.

Will close this ticket, but in case you have any follow up questions on this topic, feel free to comment / reopen.

Cheers.
