### ISSUE TITLE
Kotlin upgrade ":adjust_sdk:parseDebugLocalResources" error

### ISSUE THREAD

**Issue by mericgerceker** [adjust/flutter_sdk#69]
I am using version 4.29.1 of the package. When I update the kotlin version in my app to 1.5.31, I get the error ":adjust_sdk:parseDebugLocalResources". How can I solve it?

**Comment by uerceg** [comment]
Hi @mericgerceker 

Hm, interesting. Maybe dummy suggestion, but did you try cleaning up the project completely and rebuilding? I have just tested upgrade of the project which uses Kotlin 1.5.10 to 1.5.31 and didn't manage to reproduce this issue.

**Comment by uerceg** [comment]
Hey @mericgerceker 

Any update on this one?

**Comment by mericgerceker** [comment]
Hello @uerceg, first of all, sorry for my late reply. I created a new project and tried to upgrade the kotlin version. There was no problem. I will have to examine my project in detail. Thank you for your interest. Issue can be closed.
