### ISSUE TITLE
Build error on android

### ISSUE THREAD

**Issue by subsaha-ps** [adjust/flutter_sdk#75]
Hi team,
I am using Flutter 2.5.0 and Dart 2.14.0, I have added adjust sdk by following all the steps for Android and IOS, for IOS its working fine but for Android, build is generated but crashed as soon as launched on device.

Error: Caused by: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.

**Comment by uerceg** [comment]
Hi @subsaha-ps,

This error should not be caused by Adjust SDK. Our SDK doesn't have any dependency on Crashlytics nor any Firebase library. Not sure what might be causing this error in your app. Are you using Crashlytics maybe?

**Comment by rirjkl19** [comment]
I had the same issue. Though I'm using the latest `flutter version 2.10.1`. This happened when I'm trying to implement the adjust sdk. Which is forcing me to use a `compiledSdkVersion 32.` However after changing the version this is my error:

```
Launching .\lib\main_development.dart on sdk gphone64 x86 64 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/    110.7sandroid/generic/02 to old ns http://schemas.android.com/repository/android/generic/01Warning: Mapping new ns http://schemas..\lib\main_development.dartandroid.com/sdk/android/repo/addon2/02 to old ns http://schemaou notice graphics artifacts, consider enabling software rendering withs.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/androidn debug mode.../repo/repository2/02 to old ns http://schemas.android.com/sdk/android/common/02 to old ns http://schemas.android.com/repository/android/common/01android/repo/repository2/01                                   android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/and/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repositoryroid/repo/sys-img2/01
Running Gradle task 'assembleDebug'...                            266.6s
Exception: Gradle build failed to produce an .apk file. It's
likely that this file was generated under
C:\Development\<some_project>\build, but the toolcouldn't find it.
```

**Comment by uerceg** [comment]
Hi @subsaha-ps,

Any update on this one?
