### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method requestTrackingAuthorizationWithCompletionHandler on channel com.adjust.sdk/api

### ISSUE THREAD

**Issue by kenguyenduc** [adjust/flutter_sdk#79]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method requestTrackingAuthorizationWithCompletionHandler on channel com.adjust.sdk/api)
E/flutter ( 5174): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter ( 5174): <asynchronous suspension>
E/flutter ( 5174): #1      Adjust.requestTrackingAuthorizationWithCompletionHandler (package:adjust_sdk/adjust.dart:101:24)
E/flutter ( 5174): <asynchronous suspension>

**Comment by JakeGi** [comment]
How to solve it?

**Comment by kenguyenduc** [comment]
@uerceg Thanks for the support.
