### ISSUE TITLE
COPPA compliance and publishing flutter applications on google play

### ISSUE THREAD

**Issue by namini40** [adjust/flutter_sdk#81]
As the new Google play Families policy there were some options that has been added to **android** sdk for this issue. Are you planning on updating **flutter** sdk too or how can I use those options in flutter too?

best regards

**Comment by uerceg** [comment]
Hi @namini40,

We are working on a Flutter SDK update which will provide this functionality introduced in native SDKs. Will ping you after an update has been released.

**Comment by namini40** [comment]
thanks alot im closing the issue then. @uerceg
