### ISSUE TITLE
Getting crashlog in Firebase crashlytics 

### ISSUE THREAD

**Issue by MjCodingCamp** [adjust/flutter_sdk#99]
**adjust_sdk 4.32.0** while using adjust sdk getting app crashes in firebase crashlytics. When I try to reproduce this issue during my investigation i found the same error in debug mode on the same file (adjust.dart) & same line (101).   

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
type '_OneByteString' is not a subtype of type 'num'. Error is thrown null.
Adjust.requestTrackingAuthorizationWithCompletionHandler (adjust.dart:101)

Please resolve this issue as soon as possible.

**Comment by namini40** [comment]
can u omit that line of code?

**Comment by MjCodingCamp** [comment]
Yeah Sure,   

static Future<num> requestTrackingAuthorizationWithCompletionHandler() async {
    final num status = await _channel
        .invokeMethod('requestTrackingAuthorizationWithCompletionHandler');
    return status;
  }

Exception is **type 'String' is not a subtype of type 'num'**

**Comment by namini40** [comment]
no I meant remove the part where you using it and obtain it in some other way!
cause it expects a String while you want a num, so just use a String
